version: '3.8'

services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./images:/usr/share/nginx/html/images
      - ./:/usr/share/nginx/html:ro
    restart: always
